version: '3.7'
services:
  mongo:
    container_name: mongo
    image: mongo:4.2.6-bionic
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
    restart: on-failure
  go_web_starter:
    container_name: go_web_starter
    image: go_web_starter-local-build:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 3344:8080
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE=go-web-starter
      - APP_PORT=8080
    depends_on:
      - mongo
