name: Publish Documentation

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: |
          VERSION=$(date +%s)
          cat ~/GH_TOKEN.txt | docker login docker.pkg.github.com -u amithnair91 --password-stdin
          docker build . --file go_web_starter/Dockerfile --tag go_web_starter:${VERSION}
          docker push go_web_starter:${VERSION}
